server:
  port: 0

spring:
  application:
    name: chat-service
  config:
    activate:
      on-profile: default
  messages:
    basename: errors
  datasource:
    url: jdbc:mysql://localhost:3306/devlink-database
    username: devlink-user
    password: devlink-user
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance.id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

data:
  kafka:
    topicName: kafka-chat
    bootstrapServerUrl: localhost:9092
  stomp:
    endpoint: /ws-stomp
    sub: /sub
    pub: /pub
  page:
    offset: 0
    size: 2
    orderBy: messageTime




